// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TMM_iOS.remote {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="TmmServiceHttpSoap11Endpoint", Namespace="http://webservice.tmm")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TmmService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback signInOperationCompleted;
        
        public TmmService() {
            this.Url = "http://localhost:8080/TMM/services/TmmService.TmmServiceHttpSoap11Endpoint/";
        }
        
        public TmmService(string url) {
            this.Url = url;
        }
        
        public event signInCompletedEventHandler signInCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:signIn", RequestNamespace="http://webservice.tmm", ResponseNamespace="http://webservice.tmm", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public User signIn([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string publicIp) {
            object[] results = this.Invoke("signIn", new object[] {
                        name,
                        password,
                        publicIp});
            return ((User)(results[0]));
        }
        
        public System.IAsyncResult BeginsignIn(string name, string password, string publicIp, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("signIn", new object[] {
                        name,
                        password,
                        publicIp}, callback, asyncState);
        }
        
        public User EndsignIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        public void signInAsync(string name, string password, string publicIp) {
            this.signInAsync(name, password, publicIp, null);
        }
        
        public void signInAsync(string name, string password, string publicIp, object userState) {
            if ((this.signInOperationCompleted == null)) {
                this.signInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsignInCompleted);
            }
            this.InvokeAsync("signIn", new object[] {
                        name,
                        password,
                        publicIp}, this.signInOperationCompleted, userState);
        }
        
        private void OnsignInCompleted(object arg) {
            if ((this.signInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signInCompleted(this, new signInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entities.tmm/xsd")]
    public partial class User {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string publicIp;
        
        /// <remarks/>
        public int userId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool userIdSpecified;
    }
    
    public partial class signInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal signInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    public delegate void signInCompletedEventHandler(object sender, signInCompletedEventArgs args);
}
